# Generated by Django 4.1.5 on 2023-01-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_A', models.CharField(max_length=100)),
                ('options_B', models.CharField(max_length=100)),
                ('options_C', models.CharField(max_length=100)),
                ('options_D', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('status', models.CharField(choices=[('H', 'Hard'), ('M', 'medium'), ('E', 'easy')], max_length=10)),
                ('is_multiple_select', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqapp.chapter')),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqapp.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqapp.subject')),
            ],
        ),
    ]
