# Generated by Django 4.1.5 on 2023-01-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqapp.subject'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='question_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqapp.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
    ]
