# Generated by Django 4.1.5 on 2023-01-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0002_class_subject_name_mcq_question_text_subject_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='chapter',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqapp.class'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
