# Generated by Django 4.1.5 on 2023-01-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0004_rename_chapter_chapter_chapter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='subject',
        ),
        migrations.AlterField(
            model_name='mcq',
            name='chapter_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcqapp.chapter'),
        ),
    ]
