# Generated by Django 4.1.5 on 2023-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0005_remove_mcq_class_field_remove_mcq_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
