# Generated by Django 4.1.5 on 2023-02-03 16:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqapp', '0008_articless_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articless',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
